<?php

namespace EntityBundle\Repository;

use Doctrine\ORM\EntityRepository;
/**
 * BigFidHistoriqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BigFidHistoriqueRepository extends EntityRepository
{

}
