<?php

namespace EntityBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Back\DashBundle\Common\Tools;
use Doctrine\ORM\Tools\Pagination\Paginator;
/**
 * CommandRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandRepository extends EntityRepository
{
}
