<?php

namespace EntityBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CompagneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompagneRepository extends EntityRepository
{

}
