<?php

namespace EntityBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GpgLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GpgLogRepository extends EntityRepository
{
}
