<?php

namespace EntityBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RegleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegleRepository extends EntityRepository
{

}
