<?php

namespace EntityBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RemboursementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RemboursementRepository extends EntityRepository
{

}
