<?php

namespace EntityBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SocialmediaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SocialmediaRepository extends EntityRepository
{
}
